services:
    boobank.shell:
        class: Sam\BoobankBundle\Services\Shell
        arguments: []
    boobank:
        class: Sam\BoobankBundle\Services\Boobank
        arguments: [ "%boobank.backend_file%", "@boobank.shell" ]