services:

    boobank.shell:
        class: SamKer\BoobankPHP\Services\Shell
        arguments: []

    boobank.config:
        class: SamKer\BoobankPHP\Services\Config
        arguments: [ "%boobank%", "@boobank.shell" ]

    boobank.mailer.transport:
        class: \Swift_SmtpTransport
        arguments: [ "hello" , 25 ]

    boobank.mailer:
        class: \Swift_Mailer
        arguments: [ "@boobank.mailer.transport" ]

    boobank.twig.loader:
        class: \Twig_Loader_Filesystem

    boobank.twig:
        class: \Twig_Environment
        arguments: [ "@boobank.twig.loader" ]

    boobank:
        class: SamKer\BoobankPHP\Services\Boobank
        arguments: [ "@boobank.shell", "@boobank.config", "@boobank.mailer" , "@boobank.twig"]

    boobank.command.check:
        class: SamKer\BoobankPHP\Command\BoobankCheck
        arguments: [ "@boobank" ]

    boobank.command.backendadd:
        class: SamKer\BoobankPHP\Command\BoobankBackendAdd
        arguments: [ "@boobank"]

    boobank.command.backendlist:
        class: SamKer\BoobankPHP\Command\BoobankBackendList
        arguments: [ "@boobank"]

    boobank.command.accountlist:
        class: SamKer\BoobankPHP\Command\BoobankAccountList
        arguments: [ "@boobank"]
    boobank.command.accounthistory:
        class: SamKer\BoobankPHP\Command\BoobankAccountHistory
        arguments: [ "@boobank"]
