services:
    boobank.database:
        class: SamKer\BoobankBundle\Services\Database
        arguments: [ "@service_container" ]
    boobank.shell:
        class: SamKer\BoobankBundle\Services\Shell
        arguments: []
    boobank:
        class: SamKer\BoobankBundle\Services\Boobank
        arguments: [ "@boobank.shell", "%boobank%", "@boobank.database" , "@swiftmailer.mailer" , "%mailer_user%", "@twig"]