<?php

namespace SamKer\BoobankBundle\Repository;

use SamKer\BoobankBundle\Entity\Backends;

/**
 * BackendsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BackendsRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * get BackendEntity
     * @param $name
     * @return false|Backends
     */
    public function findByName($name)
    {
        $r = $this->findBy(["name" => $name]);
        if($r && count($r) === 1) {
            return $r[0];
        } else {
            return false;
        }
    }

    public function addBackend($backend, $module, $login, $password) {
        $em = $this->getEntityManager();
        $entityBackend = $this->findByName($backend);
        if($entityBackend) {
            throw new \Exception("backend $backend already exist in database");
            return false;
        }

        $entityBackend = new Backends();
        $entityBackend->setName($backend);
        $entityBackend->setModule($module);
        $entityBackend->setLogin($login);
        $entityBackend->setPassword($password);
        $em->persist($entityBackend);
        $em->flush();
        return $entityBackend;
    }


    /**
     * Remove backend
     *
     * @param $backend
     * @return boolean true on success
     */
    public function removeBackend($backend) {
        $em = $this->getEntityManager();
        $entityBackend = $this->findByName($backend);
        if($entityBackend) {
            $em->remove($entityBackend);
            $em->flush();
            return true;
        }
        return false;
    }
}
