<?php

namespace SamKer\BoobankBundle\Repository;
use SamKer\BoobankBundle\Entity\Accounts;
use SamKer\BoobankBundle\Entity\Backends;
use SamKer\BoobankBundle\Entity\Statements;
use Symfony\Component\Validator\Constraints\DateTime;

/**
 * StatementsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatementsRepository extends \Doctrine\ORM\EntityRepository
{

    public function findByHash($hash) {
        $r = $this->findBy(["hash"=>$hash]);
        if($r && count($r) === 1) {
            return $r[0];
        }
        return false;
    }

    /**
     * add new statement
     * @param Backends $backend
     * @param Accounts $account
     * @param string $label
     * @param DateTime $date
     * @param float $amount
     * @param string $hash
     * @return bool true on success
     * @throws \Doctrine\ORM\OptimisticLockException
     */
    public function addState($backend, $account, $label, $date, $amount, $hash) {
        if(!$this->findByHash($hash)){
            $newState = new Statements();
            $newState->setBackend($backend);
            $newState->setAccount($account);
            $newState->setAmount($amount);
            $newState->setLabel($label);
            $newState->setHash($hash);
            $newState->setDate($date);

            $em = $this->getEntityManager();
            $em->persist($newState);
            $em->flush();
            return true;
        }
        return false;



    }
}
